### ISSUE TITLE
Can not pass arguments to main.py because the conflict of mood_parser and arg_parser

### ISSUE THREAD

**Issue by ducmanhnguyen** [deeplearning-wisc/MOOD#1]
Hi,
I setup environments and data as the instructions in README. then I ran the example script you gave:

    python main.py -s energy -l 5 -a 1 -c png

but it showed the error about the arguments parser as below:

    main.py: error: argument --arch/-a: invalid choice: '1' (choose from 'msdnet', 'msdnet_ge', 'IMTA_MSDNet', 'mobilenet_imagenet')

After check the code, I realized that we have an arguments parser ``mood_parser`` in the main.py and then it import another arguments parser ``arg_parser`` from msd_args.py, and I see that the parameter ``--arch/-a`` is come from the ``arg_parser``. So probably the second parser took arguments from the first one, and lead to conflict then return error.

when I ran without arguments, it work well, since there was no arguments passed, so there is no conflict:

    python main.py

Please help us to fix this small bug. Thank you very much!

**Comment by myhakureimu** [comment]
Thank you very much for pointing it out! Will fix it in the coming days!

**Comment by ducmanhnguyen** [comment]
Hi @myhakureimu , 
Thank you for fixed the bugs. I saw you changed the arguments name by added the prefix "m" to avoid conflict. It working well now. Anyway, just a small notice that you didn't update the README for that small changed, so it may confuse the other people later :)

**Comment by myhakureimu** [comment]
Sure! Thank you!
