### ISSUE TITLE
How do I train the model?

### ISSUE THREAD

**Issue by ZZHHogan** [deeplearning-wisc/MOOD#3]
hello,How do I train the model ？I do not how to train and get the model based on my dataset?

**Comment by myhakureimu** [comment]
For training the model, please see the papers for MSD-Net (https://arxiv.org/abs/1703.09844) and (https://openaccess.thecvf.com/content_ICCV_2019/papers/Li_Improved_Techniques_for_Training_Adaptive_Deep_Networks_ICCV_2019_paper.pdf) and also their github repo.
